# Generated by Django 5.2.6 on 2025-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_education_project_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
