# Generated by Django 5.2.6 on 2025-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_skill_name_remove_skill_proficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='url_git',
        ),
        migrations.AddField(
            model_name='project',
            name='url_live',
            field=models.URLField(blank=True, null=True),
        ),
    ]
