# Generated by Django 5.2.6 on 2025-09-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_url_project_url_git_project_url_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='degree_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='company_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='key_words_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='key_words_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='key_words_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='short_description_ca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='short_description_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_ca',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_es',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url_git_backend',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_ca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_ca',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_es',
            field=models.TextField(null=True),
        ),
    ]
