# Generated by Django 5.2.6 on 2025-09-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
